<div class="container">
  <?php $ajax= $block->getBaseUrl() . 'employee/index/save'; 
  ?>
  <form id="form_value" name="form_value"  method="POST" >
    <label for="firstname">First Name</label>
    <input type="text" id="firstname" name="firstname" placeholder="Your name.." value="">
    <br><br>
    <label for="lastname">Last Name</label>
    <input type="text" id="lastname" name="lastname" placeholder="Your last name.." value="">
    <br><br>
    <label for="mobile">Mobile No</label>
    <input type="text" id="mobile" name="mobile" placeholder=" Your Mobile No " value="">
    <br><br>
    <label for="address">Address</label>
    <input type="text" id="address" name="address" placeholder=" Your Address " value="">
    <br><br>
    <br>
    <input type="submit"  value="Submit" id="testsubmit">
    <a href="<?= $block->getUrl('*/*/show')?>" 
               class="action primary">View Data</a>
  </form>

  
</div>


<script type="text/x-magento-init">
        {
            "#testsubmit": {
                "testwidget": {
                    "AjaxUrl": "<?php echo $ajax; ?>"
               }
            }
        }
</script>
